[package]
name = "rumblebars"
version = "0.0.1"
authors = ["Nicolas Cherel"]

[dependencies]
rustc-serialize = "0.3"
regex = "0.1"
regex_macros = "0.1"
rustlex = "0.2" # when it works

# for dev cycles
# [dependencies.rustlex]
# path = "../rustlex" # either this for local rustlex install
# git = "https://github.com/nicolas-cherel/rustlex" # or that for compat buffer
# branch = "rumblebars-compat"
